### ISSUE TITLE
Loss of survey option selected when user swipes to next question and returns to the same question.

### ISSUE THREAD

**Issue by apoorva-mk** [openMF/ppi-vision#14]
Whenever an answer option is selected in the app for a survey question, when the user swipes to the next question and returns back, we no longer see the selected option as selected.

**Comment by OussEmaDevCode** [comment]
@apoorva-mk I can't seem to be able to reproduce this issue: 
![video2gif_20200114_132313](https://user-images.githubusercontent.com/38397893/72344334-401e1700-36d1-11ea-80eb-e34b13a574cb.gif)

**Comment by apoorva-mk** [comment]
To recreate the issue, I would suggest you select an option on say the first question, scroll to the very end and then come back to the first question so that the Recycler View actually reuses the layouts which causes the loss of option selected.

**Comment by OussEmaDevCode** [comment]
@apoorva-mk yes, that in fact, solved the problem.
